version: '3'
services:
###################################################################################
  splunk:
    build: ./dockers/splunk
    image: splunk
    environment:
        SPLUNK_START_ARGS: --accept-license --answer-yes
        SPLUNK_ENABLE_LISTEN: 9997
        SPLUNK_PASSWORD: 5plunK99
    ports:
      - 8000:8000
      # - 8088:8088
      # - 8089:8089
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  nao_resiliente_bacen:
    build: ./Bacen
    environment:
        Serilog__Properties__Application: Nao.Resiliente.Bacen
    ports:
      - 1001:80
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./Bacen/config:/app/config
###################################################################################
  resiliente_bacen:
    build: ./Bacen
    environment:
        Serilog__Properties__Application: Resiliente.Bacen
    ports:
      - 1501:80
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./Bacen/config:/app/config
###################################################################################
  nao_resiliente_servico_a:
    build: ./Nao.Resiliente.ServicoA
    ports:
      - 2001:80
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  resiliente_servico_a:
    build: ./Resiliente.ServicoA
    ports:
      - 2501:80
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: malaca/spring-cloud-config:Hoxton.RELEASE
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  eureka:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: malaca/spring-cloud-eureka:Hoxton.RELEASE
    restart: always
    depends_on:
      - config
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  turbine:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: malaca/spring-cloud-turbine:Hoxton.RELEASE
    restart: always
    depends_on:
      - config
      - eureka
      - rabbitmq
    ports:
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  hystrix-dash:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: malaca/spring-cloud-hystrix-dash:Hoxton.RELEASE
    restart: always
    depends_on:
      - config
      - eureka
      - turbine
    ports:
      - 9999:9999
    logging:
      options:
        max-size: "10m"
        max-file: "10"