version: '3'
services:
  splunk:
    build: ./dockers/splunk
    image: splunk
    environment:
        SPLUNK_START_ARGS: --accept-license --answer-yes
        SPLUNK_ENABLE_LISTEN: 9997
        SPLUNK_PASSWORD: 5plunK99
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089
    networks:
      - compose1
  # hystrix:
  #   image: kennedyoliveira/hystrix-dashboard
  #   ports: 
  #      - 7979:7979
  #   networks:
  #     - compose1
  # servico_a:
  #   build: ./ServicoA
  #   ports:
  #     - 5000:80
  #   environment:
  #       ASPNETCORE_ENVIRONMENT: Development
    networks:
      - compose1
networks:
  compose1: