version: '3'
services:
###################################################################################
  splunk:
    build: ./dockers/splunk
    environment:
        SPLUNK_START_ARGS: --accept-license --answer-yes
        SPLUNK_ENABLE_LISTEN: 9997
        SPLUNK_PASSWORD: 5plunK99
    ports:
      - 8000:8000
      - 8088:8088
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./dockers/splunk/etc:/opt/splunk/etc      
###################################################################################
  nao_resiliente_bacen:
    build: 
      context: ./Bacen 
      args:
        httpproxy: ${HTTP_PROXY_HOST}:${HTTP_PROXY_PORT}
        httpsproxy: ${HTTPS_PROXY_HOST}:${HTTPS_PROXY_PORT}
        port: 1001
    environment:
        Serilog__Properties__Application: Nao.Resiliente.Bacen
    ports:
      - 1001:1001
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  resiliente_bacen:
    build:
      context: ./Bacen 
      args:
        httpproxy: ${HTTP_PROXY_HOST}:${HTTP_PROXY_PORT}
        httpsproxy: ${HTTPS_PROXY_HOST}:${HTTPS_PROXY_PORT}
        port: 1501
    environment:
        Serilog__Properties__Application: Resiliente.Bacen
    ports:
      - 1501:1501
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./Bacen/config:/app/config   
###################################################################################
  nao_resiliente_servico_a:
    build:
      context: ./Nao.Resiliente.ServicoA
      args:
          httpproxy: ${HTTP_PROXY_HOST}:${HTTP_PROXY_PORT}
          httpsproxy: ${HTTPS_PROXY_HOST}:${HTTPS_PROXY_PORT}
          port: 2001
    ports:
      - 2001:2001
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  resiliente_servico_a:
    build:
      context: ./Resiliente.ServicoA
      args:
          httpproxy: ${HTTP_PROXY_HOST}:${HTTP_PROXY_PORT}
          httpsproxy: ${HTTPS_PROXY_HOST}:${HTTPS_PROXY_PORT}
          port: 2501
    ports:
      - 2501:2501
    depends_on:
      - eureka
      - rabbitmq
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  config:
    build: ./dockers/spring-config
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      VAULT_DEV_ROOT_TOKEN_ID: $VAULT_DEV_ROOT_TOKEN_ID
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  eureka:
    image: malaca/spring-cloud-eureka:Hoxton.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      - config
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  turbine:
    image: malaca/spring-cloud-turbine:Hoxton.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      - config
      - eureka
      - rabbitmq
    ports:
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  hystrix-dash:
    image: malaca/spring-cloud-hystrix-dash:Hoxton.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      - config
      - eureka
      - turbine
    ports:
      - 9999:9999
    logging:
      options:
        max-size: "10m"
        max-file: "10"
###################################################################################
  vault:
    image: vault
    environment: 
      VAULT_DEV_ROOT_TOKEN_ID: $VAULT_DEV_ROOT_TOKEN_ID
    restart: always
    ports:
      - 8200:8200
###################################################################################
  vault-script:
    image: vault
    environment: 
      VAULT_DEV_ROOT_TOKEN_ID: $VAULT_DEV_ROOT_TOKEN_ID
      VAULT_ADDR: "http://vault:8200"
    command:
      - /bin/sh 
      - -c
      - |
        while ! $$(vault status &> /dev/null); do echo "Trying to connect to vault"; sleep 2; done
        sleep 5
        vault login $${VAULT_DEV_ROOT_TOKEN_ID}
        vault kv put secret/bacen 0_erro_timeout=0 1_erro_intermitente=0 2_erro_total=0
    depends_on: 
      - vault
###################################################################################
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
####################################################################################
  # redis-browser:
  #   build: ./dockers/redis-browser
  #   restart: always
  #   ports:
  #     - 7843:7843
  #   depends_on: 
  #     - redis